#!/bin/bash
#
# Postfacto, a free, open-source and self-hosted retro tool aimed at helping
# remote teams.
#
# Copyright (C) 2016 - Present Pivotal Software, Inc.
#
# This program is free software: you can redistribute it and/or modify
#
# it under the terms of the GNU Affero General Public License as
#
# published by the Free Software Foundation, either version 3 of the
#
# License, or (at your option) any later version.
#
#
#
# This program is distributed in the hope that it will be useful,
#
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
# GNU Affero General Public License for more details.
#
#
#
# You should have received a copy of the GNU Affero General Public License
#
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
set -euo pipefail

IMAGE="${IMAGE:-build-image}"
NAME="${NAME:-postfacto}"
REPOSITORY="postfacto/$NAME"

if [[ $# -ne 1 ]]; then
  echo 'usage: ./ci-push <tag>'
  echo "This will tag and deploy $IMAGE as $REPOSITORY"
  exit 1
fi

TAG=$1
MAJOR="$(echo "$TAG" | cut -d. -f1)"
MINOR="$(echo "$TAG" | cut -d. -f2)"

for VERSION_TAG in 'latest' "$MAJOR" "$MAJOR.$MINOR" "$TAG"; do
  echo "Tagging: $REPOSITORY:$VERSION_TAG"
  docker tag "$IMAGE" "$REPOSITORY:$VERSION_TAG"
done

echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

echo 'Pushing tags'
docker push "$REPOSITORY"
