#!/bin/bash
#
# Postfacto, a free, open-source and self-hosted retro tool aimed at helping
# remote teams.
#
# Copyright (C) 2016 - Present Pivotal Software, Inc.
#
# This program is free software: you can redistribute it and/or modify
#
# it under the terms of the GNU Affero General Public License as
#
# published by the Free Software Foundation, either version 3 of the
#
# License, or (at your option) any later version.
#
#
#
# This program is distributed in the hope that it will be useful,
#
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
# GNU Affero General Public License for more details.
#
#
#
# You should have received a copy of the GNU Affero General Public License
#
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
set -e

TAG=$1
REPOSITORY=postfacto/postfacto
VERSION_TAG="$REPOSITORY:$TAG"
LATEST_TAG="$REPOSITORY:latest"

echo "Tagging: $VERSION_TAG"
docker tag build-image $VERSION_TAG

echo "Tagging: $LATEST_TAG"
docker tag build-image $LATEST_TAG

#docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

echo "Pushing tag: $VERSION_TAG"
docker push $VERSION_TAG

echo "Pushing tag: $LATEST_TAG"
docker push $LATEST_TAG
