ruby '2.4.0'
source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'rspec-retry'
  gem 'capybara'
  gem 'selenium-webdriver', github: 'topherbullock/selenium', branch: 'gemspec'
  gem 'pry'
  gem 'pry-byebug'
end
