#
# Postfacto, a free, open-source and self-hosted retro tool aimed at helping
# remote teams.
#
# Copyright (C) 2016 - Present Pivotal Software, Inc.
#
# This program is free software: you can redistribute it and/or modify
#
# it under the terms of the GNU Affero General Public License as
#
# published by the Free Software Foundation, either version 3 of the
#
# License, or (at your option) any later version.
#
#
#
# This program is distributed in the hope that it will be useful,
#
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
# GNU Affero General Public License for more details.
#
#
#
# You should have received a copy of the GNU Affero General Public License
#
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source 'https://rubygems.org'

ruby '~> 2.4.0'

gem 'rails', '~> 5.1.3'

gem 'activeadmin'
gem 'addressable'
gem 'bcrypt'
gem 'devise'
gem 'friendly_id', '~> 5.1.0'
gem 'inherited_resources'
gem 'jbuilder'
gem 'premailer-rails'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'
gem 'rest-client'
gem 'uglifier'

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'shoulda-matchers'
  gem 'webmock'
end

group :development do
  gem 'sqlite3'
  gem 'bullet'
  gem 'listen'
  gem 'web-console'
end

group :production do
  gem 'cf-app-utils'
  gem 'redis', '~> 3.3.3'
  gem 'mysql2'
  gem 'pg'
end
