source 'https://rubygems.org'

ruby '~> 2.4.0'

gem 'rails', '~> 5.1.3'

gem 'activeadmin'
gem 'addressable'
gem 'bcrypt'
gem 'devise'
gem 'friendly_id', '~> 5.1.0'
gem 'inherited_resources'
gem 'jbuilder'
gem 'mysql2'
gem 'newrelic_rpm'
gem 'pg'
gem 'premailer-rails'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'
gem 'rest-client'
gem 'rollbar'
gem 'uglifier'

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'shoulda-matchers'
  gem 'webmock'
end

group :development do
  gem 'bullet'
  gem 'listen'
  gem 'web-console'
end

group :production do
  gem 'cf-app-utils'
  gem 'redis', '~> 3.3.3'
end
