#
# Postfacto, a free, open-source and self-hosted retro tool aimed at helping
# remote teams.
#
# Copyright (C) 2016 - Present Pivotal Software, Inc.
#
# This program is free software: you can redistribute it and/or modify
#
# it under the terms of the GNU Affero General Public License as
#
# published by the Free Software Foundation, either version 3 of the
#
# License, or (at your option) any later version.
#
#
#
# This program is distributed in the hope that it will be useful,
#
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
# GNU Affero General Public License for more details.
#
#
#
# You should have received a copy of the GNU Affero General Public License
#
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source 'https://rubygems.org'

ruby '2.6.3'

gem 'rails', '>= 5.2.2.1'

gem 'activeadmin', '>= 1.4.3'
gem 'addressable'
gem 'bcrypt'
gem 'cf-app-utils'
gem 'devise', '>= 4.7.1'
gem 'friendly_id'
gem 'inherited_resources', '>= 1.9.0'
gem 'jbuilder'
gem 'premailer-rails', '>= 1.10.2'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-ssl'
gem 'rest-client'
gem 'uglifier'
gem 'jwt'

group :development, :test do
  gem 'dotenv-rails', '>= 2.7.0'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rspec-rails', '>= 3.8.2'
  gem 'rubocop', require: false
  gem 'shoulda-matchers'
  gem 'webmock'
  gem 'tzinfo-data'
  gem 'climate_control'
  gem 'action-cable-testing', '>= 0.5.0'
end

group :development do
  gem 'sqlite3', '~> 1.3', '< 1.4'
  gem 'bullet'
  gem 'listen'
  gem 'web-console', '>= 3.7.0'
end

group :production do
  gem 'redis', '~> 3.3.3'
  gem 'mysql2'
  gem 'pg'
end
