# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
Rails.application.load_tasks

if ENV['RAILS_ENV'] != 'production'
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new
  task default: [:rubocop]
end

desc 'Starts the server'
task 'start' => :environment do
  system 'rails server -b 0.0.0.0 -p 4000'
end

desc 'Backfill slugs of records with id'
task 'backfill_slug' => :environment do
  Retro.where(slug: nil).each do |r|
    r.update_column(:slug, r.id)
  end
end
